version: '2.4'
services:
  fr_automation_api:
    image: ds_fr_api_server:v2_with_pandas
    build:
      context: ./app
      dockerfile: Dockerfile
    restart: unless-stopped
    network_mode: "host"
    container_name: ds_automation_api
    working_dir: /app
    volumes:
      - /TENGRI/SRC/AUTOMATION/automation_api/app:/app
      - /TENGRI/STORAGE/automation_data:/automation_data
      - /TENGRI/STORAGE/final_index:/final_index
      - /TENGRI/STORAGE/final_index_backup:/final_index_backup
      # Change above to real populated.index location in real environment
      - /var/run/docker.sock:/var/run/docker.sock
    shm_size: 1g
    ulimits:
      memlock: -1
      stack: 67108864
    command: sh -c "sleep 10s && uvicorn main:app --reload --host 0.0.0.0 --port 3333 --workers 10 --forwarded-allow-ips '*'"
    environment:
      - PROJECT_SRC_RT=${PWD}
      - LC_ALL=C.UTF-8
      - LANG=C.UTF-8
